import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeModeScript } from 'flowbite-react';
import ReduxProvidor from "../../redux/reduxProvidor";
import Header from "@/components/serverComponent/public/Header";
import Footer from "@/components/serverComponent/public/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  suppressHydrationWarning>
         <head>
                <ThemeModeScript />
            </head>
      <body>
        <ReduxProvidor>
          <Header />
        {children}
        <Footer />
        </ReduxProvidor>
      </body>
    </html>
  );
}
